apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "chart.fullname" . }}-ingress
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "api/$2"
spec:
  ingressClassName: nginx
#  tls:
#    - hosts:
#        - {{ required ".Values.ingress.host must be defined!" .Values.ingress.host }}
#      secretName: {{ required ".Values.ingress.host must be defined!" .Values.ingress.host }}-tls
  rules:
  - host: {{ required ".Values.ingress.host must be defined!" .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "chart.fullname" . }}-service
            port:
              number: 80
        path: /api/salary(/|$)(.*)
        pathType: Prefix